#+PROPERTY: header-args :tangle /Users/yaqub/.emacs.d/init.el
* Bootstrap
This section is about setting up straight.el and use-package, which we'll use to manage packages.

** Bootstrap Straight and use-package
#+begin_src emacs-lisp
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src

* Basics
** Bind-key

Need this to work in order to bind keys to packages I install.

#+begin_src emacs-lisp
(use-package bind-key
  :straight t)
#+end_src
** Mitsuharu keybindings
Make mitsuharu keybindings behave like mainline emacs (so command is the super key)
#+begin_src emacs-lisp
  (setq mac-option-modifier 'meta)     ; Set option key as META
  (setq mac-command-modifier 'super)   ; Set cmd key as SUPER
#+end_src
** Silence the bell
#+begin_src emacs-lisp 
  (setq ring-bell-function 'ignore)
#+end_src
** Silence the splash screen
#+begin_src emacs-lisp 
  (setq inhibit-startup-message t)
  (setq initial-buffer-choice t)
#+end_src
** File Backups
Backup files in a hidden ~.saves~ directory, so they don't cloud up ~ls~
#+begin_src emacs-lisp
  (setq backup-directory-alist `(("." . "~/.saves")))
  (setq backup-by-copying t)
#+end_src
** Automatically tangle this config
#+begin_src emacs-lisp
  (defun yaqub/tangle-if-org-in-yaqubmacs ()
    "If the saved file is an .org file within ~/Development/yaqubmacs, tangle it."
    (let ((target-dir (expand-file-name "~/Development/yaqubmacs")))
      (when (and (string-suffix-p ".org" buffer-file-name)
                 (eq major-mode 'org-mode)
                 (string-prefix-p target-dir buffer-file-name))
        (org-babel-tangle))))

  (add-hook 'after-save-hook 'yaqub/tangle-if-org-in-yaqubmacs)
#+end_src
* Aesthetics
This section deals with the aesthetic aspects of our Emacs setup.
** Define fonts
#+begin_src emacs-lisp
  (setq yaqub/font-monospace "Iosevka")
  (setq yaqub/font-variable-serif "CMU Serif")
  (setq yaqub/font-variable-sans "CMU Bright")
  
  ;; Ok, now define fonts on emacs' end
  (set-face-attribute 'default nil :font yaqub/font-monospace :height 180)
  (set-face-attribute 'variable-pitch nil :font yaqub/font-variable-serif :inherit 'default) 
#+end_src
** UI Changes
#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (toggle-scroll-bar -1)
  (tool-bar-mode -1)
  (set-frame-font
   (format "%s-%d" yaqub/font-monospace 18)
   nil t)
#+end_src

We can also do a transparent title bar on macOS:

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark))
#+end_src
** Install and Enable angloid-theme
#+begin_src emacs-lisp
  (use-package atom-one-dark-theme
    :straight t
    :config
    (load-theme 'atom-one-dark t))
#+end_src
** Setup all-the-icons
All-the-icons is a package to use icons in your Emacs.

#+begin_src emacs-lisp
  (use-package all-the-icons
    :straight (all-the-icons :type git :host github :repo "domtronn/all-the-icons.el" :branch "svg" :files (:defaults "svg"))
    :if (display-graphic-p))
#+end_src

We can also configure all-the-icons to be used with dired

#+begin_src emacs-lisp
  (use-package all-the-icons-dired
    :straight (all-the-icons-dired
  	     :type git
  	     :host github
  	     :repo "jtbm37/all-the-icons-dired")
    :config
    (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+end_src

** Setup modeline
*** Moody
Moody is a package for creating attractive mode-lines.

#+begin_src emacs-lisp
(use-package moody
  :straight t
  :config
  (setq x-underline-at-descent-line t)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))
#+end_src

*** Minions
Minions is a package for managing and organizing minor-mode lighters in the mode-line.

#+begin_src emacs-lisp
  (use-package minions
    :straight t
    :config
    (setq minions-mode-line-lighter "M")
    (setq minions-mode-line-delimiters '("" . ""))
    (add-to-list 'minions-prominent-modes 'org-st-andrews-mode)
    (minions-mode 1))
#+end_src

#+RESULTS:
: t

** Setup Olivetti-mode
We'll enable olivetti mode whenever we enter org mode.
#+begin_src emacs-lisp
  (use-package olivetti
    :straight t)
#+end_src
* Navigation
This section is about setting up tools that help us navigate our buffers and files more efficiently.
** Setup Ivy and Counsel
#+begin_src emacs-lisp
  (use-package ivy
    :straight t
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package counsel
    :straight t
    :bind (("C-M-j" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :config
    (counsel-mode 1))
#+end_src

** Which-Key
Which-Key is a package that displays a popup listing the possible keys to complete a command, menu, etc.

#+begin_src emacs-lisp
(use-package which-key
  :straight t
  :init
  (which-key-mode)
  :config
  ;; Reduce the delay before which-key popup appears
  (setq which-key-idle-delay 0)
  ;; Set the width of the which-key popup window
  (setq which-key-side-window-max-width 0.33)
  ;; Set the location of the which-key popup window to the bottom
  (setq which-key-side-window-location 'bottom))
#+end_src
** Setup Evil-mode
Evil-mode provides Vim keybindings in Emacs.

#+begin_src emacs-lisp
  (defun yaqub/jump-to-scratch-or-quit (orig-fun &rest args)
    "Switch to *scratch* buffer when :q is executed on single window, or quit otherwise."
    (if (one-window-p t)
        (if (not (string= (buffer-name) "*scratch*"))
            (switch-to-buffer "*scratch*"))
      (apply orig-fun args)))

  (use-package evil
    :straight t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    :config
    (evil-mode 1)
    (advice-add 'evil-quit :around 'yaqub/jump-to-scratch-or-quit))

  (use-package evil-collection
    :straight t
    :after evil
    :config
    (evil-collection-init))
#+end_src
**** Multiple cursors in evil-mode
#+begin_src emacs-lisp
  (use-package evil-mc
    :straight t
    :config
    (global-evil-mc-mode 1))
#+end_src
** Dirvish
Dirvish is an improved version of dired. Old dired settings [[id:41303942-1C05-429C-A876-858BAADB853F][here.]]

#+begin_src emacs-lisp 
  (use-package dirvish
    :straight t
    :config
    (dirvish-override-dired-mode))
#+end_src
* Coding
This section is about setting up tools to help us write code more efficiently.

** Enable line numbers in prog-mode
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

** Setup Yasnippet
Yasnippet is a template system for Emacs.

#+begin_src emacs-lisp
  (use-package yasnippet
    :straight t
    :init
    (yas-global-mode 1))
#+end_src

** Setup Company-mode
Company mode is a text completion framework.

#+begin_src emacs-lisp
  (use-package company
    :straight t
    :init
    (global-company-mode))
#+end_src

*** Setup Company-box
Company-box is a frontend for company-mode, it provides a dropdown menu interface for completions.

#+begin_src emacs-lisp
  (use-package company-box
    :straight t
    :hook (company-mode . company-box-mode))
#+end_src
** Magit
Magit is an interface to the version control system Git, implemented as an Emacs package. It aspires to be a complete Git porcelain.

#+begin_src emacs-lisp
(use-package magit
  :straight t
  :bind (("C-x g" . magit-status)))
#+end_src
** Javascript
#+begin_src emacs-lisp 
  (add-hook 'js-mode-hook
  	  (lambda ()
  	    (setq js-indent-level 2)
  	    (setq indent-tabs-mode nil)))
#+end_src
* Writing
This section is about setting up tools to help us write prose more efficiently; mostly org config.
** Global bibliography variables
#+begin_src emacs-lisp 
  (setq yaqub/global-bibliography '("~/Books/References.bib"
  			   "~/Articles/References.bib")
        yaqub/global-library-path '("~/Books/" "~/Articles/")
        yaqub/global-notes-path "~/Orgfiles/roam/references/")
#+end_src
** Setup Org
Here, we separate the org setup into its own function for clarity.

#+begin_src emacs-lisp
  (defun yaqub/org-font-setup ()
    ;; set all org levels to use variable-pitch font
    (dolist (level (number-sequence 1 8))
  	     (let* ((org-level-face (intern (format "org-level-%d" level))))
  	     (set-face-attribute org-level-face nil
  				 :font yaqub/font-variable-serif
  				 :foreground (face-attribute 'default :foreground)
  				 :weight (if (= level 1) 'bold 'normal)
  				 :height 1.0)))
    
    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-code nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block-begin-line nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block-end-line nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch)))

  (use-package org
    :straight t
    :config
    (yaqub/org-font-setup)
    (add-hook 'org-mode-hook 'variable-pitch-mode)
    (setq org-hide-emphasis-markers t)
    (setq org-startup-indented t)
    ;; org-cite-bibliography will be used for all bib-related files
    (setq org-cite-global-bibliography yaqub/global-bibliography)
    ;; Enable olivetti on all org buffers
    (add-hook 'org-mode-hook 'olivetti-mode)
    ;; add keybindings for org-mark-ring-goto at C-c C-<left> and C-c C-<right>
    (define-key org-mode-map (kbd "C-c <left>") 'org-mark-ring-goto)
    (define-key org-mode-map (kbd "C-c <right>") 'org-mark-ring-goto)
    ;; add keybindings for org-mark-ring-push at C-c C-<up> and C-c C-<down>
    (define-key org-mode-map (kbd "C-c <up>") 'org-mark-ring-push)
    (define-key org-mode-map (kbd "C-c <down>") 'org-mark-ring-push)
    )
#+end_src
*** Org-roam
Very important.
#+begin_src emacs-lisp
  (use-package org-roam
    :straight t
    :custom
    (org-roam-directory "~/Orgfiles/roam")
    :config
    (setq org-roam-capture-templates
          '(("d" "default" plain
     "%?"
     :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
     :unnarrowed t)
            
            ("r" "bibliography reference" plain
             (file "~/Orgfiles/roam/templates/orb.org")
             :target
             (file+head "references/${citekey}.org" "#+title: ${title}\n"))))
    :bind (("C-c n f" . org-roam-node-find)
           ("C-c n i" . org-roam-node-insert)
           ("C-c n g" . org-roam-graph)
           ("C-c n c" . org-roam-capture)
           ("C-c n d" . org-roam-dailies-goto-today)
           ("C-c n D" . org-roam-dailies-goto-date)))


  (defun yaqub/org-roam-setup-on-startup ()
    "Open specific roam file and today's daily note side by side on Emacs startup."
    ;; Open the specific roam file
    (find-file "/Users/yaqub/Orgfiles/roam/00000000000000-home.org"))
  ;; Add the function to the after-init-hook to ensure it runs after Emacs is fully loaded
  (add-hook 'after-init-hook 'yaqub/org-roam-setup-on-startup)
#+end_src
*** Citar
This plugin provides the basic functionality of ~org-ref~, but uses the ~org-cite~ syntax instead of breaking with what's built into emacs.

#+begin_src emacs-lisp
  (use-package citar
    :straight t
    :config
    (global-set-key (kbd "C-c c o") 'citar-open)
    (global-set-key (kbd "C-c c i") 'citar-insert-citation)
    (global-set-key (kbd "C-c c n") 'citar-open-notes)
    (global-set-key (kbd "C-c c r") 'citar-refresh)
    :custom
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'citar)
    (citar-bibliography '("~/Books/References.bib" "~/Articles/References.bib"))
    (citar-notes-paths '("~/Orgfiles/roam/references/"))
    (citar-file-note-extensions '("org" "md"))
    :hook
    (LaTeX-mode . citar-capf-setup)
    (org-mode . citar-capf-setup))

  (use-package citar-org-roam
    :after (citar org-roam)
    :config (citar-org-roam-mode))
#+end_src

*** Org-modern
Only temporarily re-deploying org-modern, until the font locking issue is fixed in svg-tag-mode (cf. [[https://github.com/rougier/svg-tag-mode/issues/48][issue]])

#+begin_src emacs-lisp
  (use-package org-modern
    :straight t
    :config
    (global-org-modern-mode))
#+end_src
*** Org-dashboard
#+begin_src emacs-lisp
  (use-package org-dashboard
    :straight t)
#+end_src
*** Org-noter
#+begin_src emacs-lisp
  (use-package org-noter
    :after (:all org nov pdf-tools)
    :straight
               (:repo "org-noter/org-noter"
                      :host github
                      :type git
                      :files ("*.el" "modules/*.el")))

  (defun yaqub/org-noter-here (&optional arg)
    (interactive "P")
    (let ((org-noter-always-create-frame nil))
      (org-noter arg)))

  (global-set-key (kbd "C-c N") 'yaqub/org-noter-here)
#+end_src
*** Org-mind-map
Disabled, code [[id:D76D48CF-9534-4FAF-A566-805E2EC3EF4A][here]]
*** Org publishing sites
#+begin_src emacs-lisp
  ;; Custom function to publish Org files with Eleventy frontmatter and customized HTML
  (defun hcol-org-html-publish-to-html (plist filename pub-dir)
    (let ((project-name (plist-get plist :publishing-project-name)))
      (when (string= (hcol-org-roam-get-publish-site filename) project-name)
        ;; Generate frontmatter
        (let ((frontmatter (hcol-org-roam-create-eleventy-frontmatter filename)))
          ;; Customize HTML output
          (org-publish-org-to 'html filename ".html" (list :with-toc nil :html-preamble frontmatter) pub-dir)))))

  ;; Function to create Eleventy frontmatter from Org properties
  (defun hcol-org-roam-create-eleventy-frontmatter (filename)
    "Create Eleventy frontmatter from Org file properties."
    (with-temp-buffer
      (insert-file-contents filename)
      (org-mode)
      (let* ((title (hcol-org-roam-get-title filename))
             (date (hcol-org-roam-get-date filename))
             (id (hcol-org-roam-get-id filename))
             (layout (or (org-entry-get (point-min) "ELEVENTY_LAYOUT") "post"))
             (custom-props (hcol-org-roam-get-custom-eleventy-props)))
        (concat "---\ntitle: " title "\ndate: " date "\nid: " id "\nlayout: " layout "\n" custom-props "---\n"))))

  ;; Function to get Org Roam file title
  (defun hcol-org-roam-get-title (filename)
    "Extract the title from the Org file."
    (with-temp-buffer
      (insert-file-contents filename)
      (org-mode)
      (or (org-entry-get (point-min) "TITLE") (file-name-base filename))))

  ;; Function to get Org Roam file date
  (defun hcol-org-roam-get-date (filename)
    "Extract the date from the Org file."
    (with-temp-buffer
      (insert-file-contents filename)
      (org-mode)
      (or (org-entry-get (point-min) "DATE") (format-time-string "%Y-%m-%d"))))

  ;; Function to get Org Roam file ID
  (defun hcol-org-roam-get-id (filename)
    "Extract the ID from the Org file."
    (with-temp-buffer
      (insert-file-contents filename)
      (org-mode)
      (or (org-entry-get (point-min) "ID") (file-name-nondirectory filename))))

  ;; Function to get custom Eleventy properties from Org file
  (defun hcol-org-roam-get-custom-eleventy-props ()
    "Extract custom Eleventy properties from Org file."
    (with-temp-buffer
      (insert-file-contents (buffer-file-name))
      (org-mode)
      (let ((props '()))
        (org-map-entries
         (lambda ()
           (let ((key (org-entry-get (point) "ELEVENTY"))
                 (value (org-entry-get (point) "ELEVENTY")))
             (when key
               (push (format "%s: %s" (substring key 9) value) props)))))
        (mapconcat 'identity props "\n"))))

  ;; Function to get the PUBLISH_SITE property
  (defun hcol-org-roam-get-publish-site (filename)
    "Read the PUBLISH_SITE property from the given file."
    (with-temp-buffer
      (insert-file-contents filename)
      (org-mode)
      (org-entry-get (point-min) "PUBLISH_SITE")))

  ;; Configuration for org-publish-project-alist
  (setq org-publish-project-alist
        '(("jpw24.hcol.uk"
           :base-directory "~/Orgfiles/roam"
           :publishing-directory "~/Development/hcol/jpw24.hcol.uk"
           :publishing-function hcol-org-html-publish-to-html
           :publishing-project-name "jpw24.hcol.uk")
          ("hcol.uk"
           :base-directory "~/Orgfiles/roam"
           :publishing-directory "~/Development/hcol/hcol.uk"
           :publishing-function hcol-org-html-publish-to-html
           :publishing-project-name "hcol.uk")))
#+end_src

*** Making sure org links open in the same window
#+begin_src emacs-lisp
    (setq org-link-frame-setup '((file . find-file)))
#+end_src
*** Lecture notes
#+begin_src emacs-lisp
  (defun org-insert-lecture-notes ()
    "Create a new Org-roam node for lecture notes and link it in the current buffer."
    (interactive)
    (let* ((current-node (org-roam-node-read)) ; Get the current Org-roam node
           (current-node-title (org-roam-node-title current-node)) ; Get the title of the current node
           (date-string (format-time-string "%Y-%m-%d")) ; Get the current date in longform
           (new-node-title (format "%s - %s" current-node-title date-string)) ; Create the new node title
           (description (read-string "Enter description: ")) ; Prompt for description
           (new-node (org-roam-capture- :node (org-roam-node-create :title new-node-title) ; Create the new node
                                        :templates '(("d" "default" "* %?" :if-new (file+head "${slug}.org" "#+title: ${title}\n")))))
           (new-node-link (org-link-make-string (concat "id:" (org-roam-node-id new-node)) new-node-title))) ; Create a link to the new node
      (insert (format "** %s - %s\n" new-node-link description)))) ; Insert the new heading with the link and description

#+end_src
** Setup LaTeX
*** Function that automatically makes latex files
#+begin_src emacs-lisp 
  (defun nlatex ()
    "Create a new LaTeX file in '~/Homework/LaTeX/', named with the current date and a user-provided string, and insert the 'ndoc' yasnippet."
    (interactive)
    (let* ((base-dir "~/Homework/LaTeX/")
           (date-str (format-time-string "%Y%m%d"))
           (name (read-string "Enter file name: "))
           (sanitized-name (replace-regexp-in-string "[^[:alnum:]]" "-" name))
           (filename (format "%s%s-%s.tex" base-dir date-str sanitized-name)))
      (unless (file-exists-p base-dir)
        (make-directory base-dir t))
      (find-file filename)
      (yas-expand-snippet (yas-lookup-snippet "ndoc"))))

#+end_src
** LaTeX preview pane
#+begin_src emacs-lisp 
  (use-package latex-preview-pane
    :config
    (latex-preview-pane-enable))
#+end_src

* Reading
** Using PDF-Tools instead of DocView
#+begin_src emacs-lisp 
  (use-package pdf-tools
    :ensure t
    :config
    ;; Ensure pdf-tools is initialized after installation
    (pdf-tools-install)

    ;; Make sure PDFs fit the page by default
    (setq-default pdf-view-display-size 'fit-page)

    ;; Set pdf-view-mode as the default for PDF files
    (add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-view-mode))
    (setq pdf-cache-prefetch-delay 0.1)
    ;; Optional: open PDFs in a new frame by default
    ;; (setq pdf-view-use-new-open t)
    ;; set keybindings
    ;; s-left: image-forward-hscroll 5
    ;; s-right: image-backward-hscroll 5
    ;; s-up: image-previous-line 5
    ;; s-down: image-next-line 5
    (define-key pdf-view-mode-map (kbd "s-<left>") 'image-forward-hscroll)
    (define-key pdf-view-mode-map (kbd "s-<right>") 'image-backward-hscroll)
    (define-key pdf-view-mode-map (kbd "s-<up>") 'image-previous-line)
    (define-key pdf-view-mode-map (kbd "s-<down>") 'image-next-line)
    ;; ok now make it scroll 5x faster
    (define-key pdf-view-mode-map (kbd "C-s-<left>") (lambda () (interactive) (image-forward-hscroll 5)))
    (define-key pdf-view-mode-map (kbd "C-s-<right>") (lambda () (interactive) (image-backward-hscroll 5)))
    (define-key pdf-view-mode-map (kbd "C-s-<up>") (lambda () (interactive) (image-previous-line 5)))
    (define-key pdf-view-mode-map (kbd "C-s-<down>") (lambda () (interactive) (image-next-line 5)))
  )
#+end_src

#+RESULTS:
: t

** /nov.el/ support
Using nov.el for epub reading
#+begin_src emacs-lisp
  (use-package nov
    :straight t
    :mode ("\\.epub\\'" . nov-mode)
    :config
    ;; enable olivetti on all nov buffers
    (add-hook 'nov-mode-hook 'olivetti-mode))
#+end_src
** Use webkit with /nov-xwidget/
Render books in Tim Applevision instead of Stallmanvision.
#+begin_src emacs-lisp
  (use-package nov-xwidget
    :straight (:host github :repo "chenyanming/nov-xwidget")
    :demand t
    :after nov
    :config
    (define-key nov-mode-map (kbd "o") 'nov-xwidget-view)
    (add-hook 'nov-mode-hook 'nov-xwidget-inject-all-files))
#+end_src
** Integrate with Calibre
Use calibre db.
#+begin_src emacs-lisp
  (defun yaqub/calibredb-export-bibtex ()
    (interactive)
    (let ((bibtex-command "calibredb catalog ~/Books/References.bib"))
      (shell-command bibtex-command)))

  (use-package calibredb
    :defer t
    :config
    (setq calibredb-root-dir "~/Books")
    (setq calibredb-db-dir (expand-file-name "metadata.db" calibredb-root-dir))
    (evil-set-initial-state 'calibredb-search-mode 'emacs))
#+end_src
** Text-to-speech 
#+begin_src emacs-lisp 
  ;; Function to speak selected text using macOS's say command
  (defun macos-speak-region (start end)
    "Speak text between START and END using macOS's say command."
    (interactive "r")
    (unless (eq major-mode 'pdf-view-mode)
      (let ((text (buffer-substring-no-properties start end)))
        (start-process-shell-command "macos-speak" nil "say" text)
        (deactivate-mark))))

  ;; Function to speak the entire buffer
  (defun macos-speak-buffer ()
    "Speak the entire buffer using macOS's say command."
    (interactive)
    (macos-speak-region (point-min) (point-max)))

  ;; Function to speak selected text in a PDF opened with pdf-tools
  (defun macos-speak-pdf-selection ()
    "Speak the selected text in a PDF opened with pdf-tools."
    (interactive)
    (when (eq major-mode 'pdf-view-mode)
      (let ((text (mapconcat 'identity (pdf-view-active-region-text) " ")))
        (unless (string-blank-p text)
          (start-process-shell-command "macos-speak" nil "say" text)
          (pdf-view-deactivate-region)))))

  ;; Function to speak the entire text of the current PDF page
  (defun macos-speak-pdf-page ()
    "Speak the text of the current PDF page."
    (interactive)
    (when (eq major-mode 'pdf-view-mode)
      (let ((text (mapconcat 'identity (pdf-view-active-region-text) " ")))
        (unless (string-blank-p text)
          (start-process-shell-command "macos-speak" nil "say" text)))))

  ;; Keybindings
  (global-set-key (kbd "C-c s") 'macos-speak-region)
  (global-set-key (kbd "C-c M-s") 'macos-speak-buffer)

  (with-eval-after-load 'pdf-view
    (define-key pdf-view-mode-map (kbd "C-c s") 'macos-speak-pdf-selection)
    (define-key pdf-view-mode-map (kbd "C-c M-s") 'macos-speak-pdf-page))
#+end_src

* EAF
Disabled, old code [[id:9073108A-6DBD-4411-9CEF-03C78ED67754][here]].
* macOS
** macOS fullscreen
#+begin_src emacs-lisp 
  (setq ns-use-native-fullscreen t)
#+end_src
** macOS Mouse
I'm using mitsuharu emacs now, so I'll set mouse scrolling to behave according to my zoomer inclinations

#+begin_src emacs-lisp
  (setq mac-mouse-wheel-smooth-scroll t)
#+end_src

** Property lists
OSX Plist is a library for reading and writing property lists (`.plist` files) as used in OS X.

#+begin_src emacs-lisp
  (use-package osx-plist
    :straight (:host github :repo "gonewest818/osx-plist"))
#+end_src

In addition, emacs should recognize everything that ends in *.plist as XML and do syntax highlighting / company suggestions / etc appropriately.

#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.plist\\'" . xml-mode))
#+end_src 

* Email
** smtpmail-multi
#+BEGIN_SRC emacs-lisp
(use-package smtpmail-multi
  :straight t)
#+END_SRC
** Gnus
#+BEGIN_SRC emacs-lisp
(use-package gnus
  :straight t
  :config
  (load "~/.gnus.el"))
#+END_SRC
* AI Tools
Currently, this is in a later part of the config because of my ~ns-keychain~ functions that I'm using for the username and password(s) and API keys and stuff. Dunno if this is the best idea.
** Github Copilot
A lot of the functions here are stolen and very-slightly-modified from Robert Krahn's [[https://robert.kra.hn/posts/2023-02-22-copilot-emacs-setup][blog post]] on setting up Copilot in emacs.

#+begin_src emacs-lisp
  (use-package copilot
    :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
    :ensure t
    :config
    (define-key copilot-mode-map (kbd "C-s-<next>") #'copilot-next-completion)
    (define-key copilot-mode-map (kbd "C-s-<prior>") #'copilot-previous-completion)
    (define-key copilot-mode-map (kbd "C-s-<right>") #'copilot-accept-completion-by-word)
    (define-key copilot-mode-map (kbd "C-s-<down>") #'copilot-accept-completion-by-line)
    (define-key global-map (kbd "C-s-<return>") #'yaqub/copilot-complete-or-accept))

  (defun yaqub/copilot-complete-or-accept ()
    "Command that either triggers a completion or accepts one if one
  is available. Useful if you tend to hammer your keys like I do."
    (interactive)
    ;; Turn on copilot-mode if it's not already active
    (unless (bound-and-true-p copilot-mode)
      (copilot-mode 1))
    (if (copilot--overlay-visible)
        (progn
          (copilot-accept-completion)
          (open-line 1)
          (next-line))
      (copilot-complete)))
#+end_src 

#+RESULTS:
: yaqub/copilot-complete-or-accept

* Minibuffer Shortcuts
#+begin_src emacs-lisp 
  ;; the command "eval-init" evaluates init.el
  (defun eval-init ()
    (interactive)
    (load-file "~/.emacs.d/init.el"))

  ;; the command "home" opens dired at ~/
  (defun home ()
    (interactive)
    (find-file "~/Orgfiles/roam/00000000000000-home.org"))

  ;; the command "yaqubmacs" opens dired at ~/Development/yaqubmacs
  (defun yaqubmacs ()
    (interactive)
    (dired "~/Development/yaqubmacs"))
#+end_src
* St Andrews Mode

#+begin_src emacs-lisp
  ;; eval org-st-andrews-mode.el from ~/.emacs.d
  (load-file "~/.emacs.d/org-st-andrews-mode.el")

#+end_src
