#+PROPERTY: header-args :tangle /Users/yaqub/.emacs.d/init.el
* Bootstrap
This section is about setting up straight.el and use-package, which we'll use to manage packages.

** Bootstrap Straight and use-package
#+begin_src emacs-lisp
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src

* Basics
** Bind-key

Need this to work in order to bind keys to packages I install.

#+begin_src emacs-lisp
(use-package bind-key
  :straight t)
#+end_src
** Mitsuharu keybindings
Make mitsuharu keybindings behave like mainline emacs (so command is the super key)
#+begin_src emacs-lisp
  (setq mac-option-modifier 'meta)     ; Set option key as META
  (setq mac-command-modifier 'super)   ; Set cmd key as SUPER
#+end_src
** Silence the bell
#+begin_src emacs-lisp 
  (setq ring-bell-function 'ignore)
#+end_src
** Silence the splash screen
#+begin_src emacs-lisp 
  (setq inhibit-startup-message t)
  (setq initial-buffer-choice t)
#+end_src
** File Backups
Backup files in a hidden ~.saves~ directory, so they don't cloud up ~ls~
#+begin_src emacs-lisp
  (setq backup-directory-alist `(("." . "~/.saves")))
  (setq backup-by-copying t)
#+end_src
** Automatically tangle this config
#+begin_src emacs-lisp
  (defun yaqub/tangle-if-org-in-yaqubmacs ()
    "If the saved file is an .org file within ~/Development/yaqubmacs, tangle it."
    (let ((target-dir (expand-file-name "~/Development/yaqubmacs")))
      (when (and (string-suffix-p ".org" buffer-file-name)
                 (eq major-mode 'org-mode)
                 (string-prefix-p target-dir buffer-file-name))
        (org-babel-tangle))))

  (add-hook 'after-save-hook 'yaqub/tangle-if-org-in-yaqubmacs)
#+end_src

* Authentication using authinfo
#+begin_src emacs-lisp
  (use-package auth-source
    :config
    ;; Optionally, specify the path to your authinfo file if it's not in the default location
    (setq auth-sources '("~/.authinfo"))
    
    ;; Function to easily retrieve passwords
    (defun my-get-password (host user)
      (let ((creds (auth-source-user-and-password host user)))
        (if creds
            (nth 1 creds)
          (error "No credentials found for %s@%s" user host))))
    
    ;; Function to easily retrieve API keys or passwords
    (defun my-get-api-key (host)
      (let ((creds (auth-source-search :host host :max 1)))
        (if creds
            (funcall (plist-get (car creds) :secret))
          (error "No API key found for %s" host))))
    
    ;; Example usage for setting a variable (adjust the variable name as needed)
    ;; (setq some-service-api-key (my-get-api-key "example.com"))
  )

#+end_src
* Aesthetics
This section deals with the aesthetic aspects of our Emacs setup.
** Define fonts
#+begin_src emacs-lisp
  (setq yaqub/font-monospace "Vulf Mono")
  (setq yaqub/font-variable-serif "CMU Serif")
  (setq yaqub/font-variable-sans "Vulf Sans")

  ;; Ok, now define fonts on emacs' end
  (set-face-attribute 'default nil :font yaqub/font-monospace :height 140)
  (set-face-attribute 'fixed-pitch nil :font yaqub/font-monospace :height 140)
  (set-face-attribute 'variable-pitch nil :font yaqub/font-variable-serif :inherit 'default) 
#+end_src


** UI Changes
#+begin_src emacs-lisp
  (menu-bar-mode 1)
  (toggle-scroll-bar -1)
  (tool-bar-mode -1)
  (set-frame-font
   (format "%s-%d" yaqub/font-monospace 14)
   nil t)
#+end_src

We can also do a transparent title bar on macOS:

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark))
#+end_src
** Install and Enable angloid-theme
#+begin_src emacs-lisp
   (use-package tao-theme
     :straight t
     :config
     (load-theme 'tao-yin t))
#+end_src

#+RESULTS:
: t

** Setup all-the-icons
All-the-icons is a package to use icons in your Emacs.

#+begin_src emacs-lisp
  (use-package all-the-icons
    :straight (all-the-icons :type git :host github :repo "domtronn/all-the-icons.el" :branch "svg" :files (:defaults "svg"))
    :if (display-graphic-p))
#+end_src

We can also configure all-the-icons to be used with dired

#+begin_src emacs-lisp
  (use-package all-the-icons-dired
    :straight (all-the-icons-dired
  	     :type git
  	     :host github
  	     :repo "jtbm37/all-the-icons-dired")
    :config
    (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+end_src

** Setup modeline
*** Moody
Moody is a package for creating attractive mode-lines.

#+begin_src emacs-lisp
(use-package moody
  :straight t
  :config
  (setq x-underline-at-descent-line t)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))
#+end_src

*** Minions
Minions is a package for managing and organizing minor-mode lighters in the mode-line.

#+begin_src emacs-lisp
  (use-package minions
    :straight t
    :config
    (setq minions-mode-line-lighter "M")
    (setq minions-mode-line-delimiters '("" . ""))
    (add-to-list 'minions-prominent-modes 'org-st-andrews-mode)
    (minions-mode 1))
#+end_src

** Setup Olivetti-mode
We'll enable olivetti mode whenever we enter org mode.
#+begin_src emacs-lisp
  (use-package olivetti
    :straight t)
#+end_src
* Navigation
This section is about setting up tools that help us navigate our buffers and files more efficiently.
** Setup Ivy and Counsel
#+begin_src emacs-lisp
  (use-package ivy
    :straight t
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package counsel
    :straight t
    :bind (("C-M-j" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :config
    (counsel-mode 1))
#+end_src

** Which-Key
Which-Key is a package that displays a popup listing the possible keys to complete a command, menu, etc.

#+begin_src emacs-lisp
(use-package which-key
  :straight t
  :init
  (which-key-mode)
  :config
  ;; Reduce the delay before which-key popup appears
  (setq which-key-idle-delay 0)
  ;; Set the width of the which-key popup window
  (setq which-key-side-window-max-width 0.33)
  ;; Set the location of the which-key popup window to the bottom
  (setq which-key-side-window-location 'bottom))
#+end_src
** Setup Evil-mode
Evil-mode provides Vim keybindings in Emacs.

#+begin_src emacs-lisp
  (defun yaqub/jump-to-scratch-or-quit (orig-fun &rest args)
    "Switch to *scratch* buffer when :q is executed on single window, or quit otherwise."
    (if (one-window-p t)
        (if (not (string= (buffer-name) "*scratch*"))
            (switch-to-buffer "*scratch*"))
      (apply orig-fun args)))

  (use-package evil
    :straight t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-undo-system 'undo-redo)
    :config
    (evil-mode 1)
    (advice-add 'evil-quit :around 'yaqub/jump-to-scratch-or-quit))

  (use-package evil-collection
    :straight t
    :after evil
    :config
    (evil-collection-init))
#+end_src

**** Multiple cursors in evil-mode
#+begin_src emacs-lisp
  (use-package evil-mc
    :straight t
    :config
    (global-evil-mc-mode 1))
#+end_src
** Dirvish
Dirvish is an improved version of dired. Old dired settings [[id:41303942-1C05-429C-A876-858BAADB853F][here.]]

#+begin_src emacs-lisp 
  (use-package dirvish
    :straight t
    :config
    (dirvish-override-dired-mode))
#+end_src
* Coding
This section is about setting up tools to help us write code more efficiently.

** Enable line numbers in prog-mode
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src
** Enable whitespace cleanup in prog-mode
#+begin_src emacs-lisp
    ;; Define a function to clean up whitespace in the buffer
    (defun yaqub/cleanup-buffer-whitespace ()
      "Clean up whitespace in the buffer, including converting tabs to spaces."
      (interactive)
      (whitespace-cleanup))

    ;; Define a function to set the key binding in programming modes
    (defun yaqub/set-cleanup-whitespace-key ()
      (local-set-key (kbd "C-c w") 'yaqub/cleanup-buffer-whitespace))

    ;; Add the key binding function to the prog-mode-hook
    (add-hook 'prog-mode-hook 'yaqub/set-cleanup-whitespace-key) 
#+end_src
** Setup Yasnippet
Yasnippet is a template system for Emacs.

#+begin_src emacs-lisp
  (use-package yasnippet
    :straight t
    :init
    (yas-global-mode 1))
#+end_src

** Setup Company-mode
Company mode is a text completion framework.

#+begin_src emacs-lisp
  (use-package company
    :straight t
    :init
    (global-company-mode))
#+end_src

*** Setup Company-box
Company-box is a frontend for company-mode, it provides a dropdown menu interface for completions.

#+begin_src emacs-lisp
  (use-package company-box
    :straight t
    :hook (company-mode . company-box-mode))
#+end_src

** Setup Editorconfig 
#+begin_src emacs-lisp 
  (use-package editorconfig
    :ensure t
    :config
    (editorconfig-mode 1))
#+end_src
** Magit
Magit is an interface to the version control system Git, implemented as an Emacs package. It aspires to be a complete Git porcelain.

#+begin_src emacs-lisp
(use-package magit
  :straight t
  :bind (("C-x g" . magit-status)))
#+end_src
** Applescript
#+begin_src emacs-lisp
  (use-package applescript-mode
    :straight (applescript-mode :type git :host github :repo "emacsorphanage/applescript-mode"))
#+end_src

* Writing
This section is about setting up tools to help us write prose more efficiently; mostly org config.
** Global bibliography variables
#+begin_src emacs-lisp 
  (setq yaqub/global-bibliography '("~/Zotero/References.bib")
        yaqub/global-library-path '("~/Zotero")
        yaqub/global-notes-path "~/Orgfiles/roam/references/")
#+end_src
** Setup Org
Here, we separate the org setup into its own function for clarity.

#+begin_src emacs-lisp
  (defun yaqub/org-font-setup ()
    ;; set all org levels to use variable-pitch font
    (dolist (level (number-sequence 1 8))
  	     (let* ((org-level-face (intern (format "org-level-%d" level))))
  	     (set-face-attribute org-level-face nil
  				 :font yaqub/font-monospace
  				 :foreground (face-attribute 'default :foreground)
  				 :weight (if (= level 1) 'bold 'normal)
  				 :height 1.0)))
    
    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-code nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block-begin-line nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block-end-line nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch)))

  (use-package org
    :straight t
    :config
    (yaqub/org-font-setup)
    (setq org-hide-emphasis-markers t)
    (setq org-startup-indented t)
    ;; org-cite-bibliography will be used for all bib-related files
    (setq org-cite-global-bibliography yaqub/global-bibliography)
    ;; Enable olivetti on all org buffers
    (add-hook 'org-mode-hook 'olivetti-mode)
    ;; add keybindings for org-mark-ring-goto at C-c C-<left> and C-c C-<right>
    (define-key org-mode-map (kbd "C-c <left>") 'org-mark-ring-goto)
    (define-key org-mode-map (kbd "C-c <right>") 'org-mark-ring-goto)
    ;; add keybindings for org-mark-ring-push at C-c C-<up> and C-c C-<down>
    (define-key org-mode-map (kbd "C-c <up>") 'org-mark-ring-push)
    (define-key org-mode-map (kbd "C-c <down>") 'org-mark-ring-push)
    )
#+end_src

#+RESULTS:
: t

*** Org-roam
Very important.
#+begin_src emacs-lisp
  (use-package org-roam
    :straight t
    :custom
    (org-roam-directory "~/Orgfiles/roam")
    :bind (("C-c n f" . org-roam-node-find)
           ("C-c n i" . org-roam-node-insert)
           ("C-c n g" . org-roam-graph)
           ("C-c n c" . org-roam-capture)
           ("C-c n d" . org-roam-dailies-goto-today)
           ("C-c n D" . org-roam-dailies-goto-date)))


  (defun yaqub/org-roam-setup-on-startup ()
    "Open specific roam file and today's daily note side by side on Emacs startup."
    ;; Open the specific roam file
    (find-file "/Users/yaqub/Orgfiles/roam/00000000000000-home.org"))
  ;; Add the function to the after-init-hook to ensure it runs after Emacs is fully loaded
  (add-hook 'after-init-hook 'yaqub/org-roam-setup-on-startup)
#+end_src
*** Citar
This plugin provides the basic functionality of ~org-ref~, but uses the ~org-cite~ syntax instead of breaking with what's built into emacs.

#+begin_src emacs-lisp
  (use-package citar
    :straight t
    :config
    (global-set-key (kbd "C-c c o") 'citar-open)
    (global-set-key (kbd "C-c c i") 'citar-insert-citation)
    (global-set-key (kbd "C-c c n") 'citar-open-notes)
    (global-set-key (kbd "C-c c r") 'citar-refresh)
    :custom
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'citar)
    (citar-bibliography '("~/Zotero/References.bib"))
    (citar-notes-paths '("~/Orgfiles/roam/references/"))
    (citar-file-note-extensions '("org" "md"))
    :hook
    (LaTeX-mode . citar-capf-setup)
    (org-mode . citar-capf-setup))

  (use-package citar-org-roam
    :after (citar org-roam)
    :config (citar-org-roam-mode))
#+end_src

*** Org-modern
Only temporarily re-deploying org-modern, until the font locking issue is fixed in svg-tag-mode (cf. [[https://github.com/rougier/svg-tag-mode/issues/48][issue]])

#+begin_src emacs-lisp
  (use-package org-modern
    :straight t
    :config
    (global-org-modern-mode))
#+end_src
*** Org-dashboard
#+begin_src emacs-lisp
  (use-package org-dashboard
    :straight t)
#+end_src
*** Org-noter
#+begin_src emacs-lisp
  (use-package org-noter
    :after (:all org nov pdf-tools)
    :straight
               (:repo "org-noter/org-noter"
                      :host github
                      :type git
                      :files ("*.el" "modules/*.el")))

  (defun yaqub/org-noter-here (&optional arg)
    (interactive "P")
    (let ((org-noter-always-create-frame nil))
      (org-noter arg)))

  (global-set-key (kbd "C-c N") 'yaqub/org-noter-here)
#+end_src
*** Making sure org links open in the same window
#+begin_src emacs-lisp
    (setq org-link-frame-setup '((file . find-file)))
#+end_src
** Setup LaTeX
*** Set up AucTeX
#+begin_src emacs-lisp 
  (use-package auctex
    :ensure t
    :mode ("\\.tex\\'" . LaTeX-mode)
    :config
    (setq TeX-auto-save t)
    (setq TeX-parse-self t)
    (setq-default TeX-master nil)

    (add-hook 'LaTeX-mode-hook 'visual-line-mode)
    (add-hook 'LaTeX-mode-hook 'flyspell-mode)
    (add-hook 'LaTeX-mode-hook 'LaTeX-math-mode)

    (add-hook 'LaTeX-mode-hook 'turn-on-reftex)
    (setq reftex-plug-into-AUCTeX t)
    (setq TeX-PDF-mode t)

    ;; Use Biber with AUCTeX
    (setq TeX-command-BibTeX "Biber"))

     ;; Function to compile LaTeX and refresh PDF view
  (defun my-latex-compile ()
    "Compile LaTeX and refresh PDF view."
    (interactive)
    (let ((pdf-file (concat (file-name-sans-extension (TeX-master-file)) ".pdf")))
      (TeX-save-document (TeX-master-file))
      (TeX-command "LaTeX" 'TeX-master-file)
      ;; Refresh PDF buffer if it's open
      (when (get-buffer pdf-file)
        (with-current-buffer pdf-file
          (revert-buffer t t t)))))
    
  ;; Hook to auto-compile on save and view PDF
  (add-hook 'LaTeX-mode-hook
            (lambda ()
              (add-hook 'after-save-hook (lambda () (message "saved!")) nil 'make-it-local)))

  (add-hook 'TeX-mode-hook
            (lambda ()
              (add-hook 'after-save-hook (lambda () (message "saved!")) nil 'make-it-local)))
#+end_src

#+RESULTS:
| lambda | nil | (add-hook 'after-save-hook (lambda nil (message saved!)) nil 'make-it-local) |

*** Function that automatically makes latex files
#+begin_src emacs-lisp 
  (defun nlatex ()
    "Create a new LaTeX file in '~/Homework/LaTeX/', named with the current date and a user-provided string, and insert the 'ndoc' yasnippet."
    (interactive)
    (let* ((base-dir "~/Homework/LaTeX/")
           (date-str (format-time-string "%Y%m%d"))
           (name (read-string "Enter file name: "))
           (sanitized-name (replace-regexp-in-string "[^[:alnum:]]" "-" name))
           (filename (format "%s%s-%s.tex" base-dir date-str sanitized-name)))
      (unless (file-exists-p base-dir)
        (make-directory base-dir t))
      (find-file filename)
      (yas-expand-snippet (yas-lookup-snippet "ndoc"))))

#+end_src
*** Function that gives word count of latex file
#+begin_src emacs-lisp 
  (defun lwc ()
    "Counts words in a PDF file corresponding to a .tex file or directly in a PDF file."
    (interactive)
    (let* ((file-name (buffer-file-name))
           (extension (file-name-extension file-name))
           (base-name (file-name-sans-extension file-name)))
      (cond ((string-equal extension "tex")
             (let ((pdf-file (concat base-name ".pdf")))
               ;; Compile .tex to .pdf if necessary. This step might need customization.
               ;; (shell-command (concat "pdflatex " file-name))
               ;; Now count the words in the PDF.
               (if (file-exists-p pdf-file)
                   (shell-command (concat "pdftotext " pdf-file " - | wc -w"))
                 (message "PDF file does not exist. Please compile your LaTeX file first."))))
            ((string-equal extension "pdf")
             (shell-command (concat "pdftotext " file-name " - | wc -w")))
            (t (message "This function is only intended for .tex and .pdf files.")))))

#+end_src
** Setup Pandoc
#+begin_src emacs-lisp
  (use-package pandoc
    :straight (pandoc :type git :host github :repo "yaqubroli/pandoc.el")
    :config
    (setq pandoc-citation-styles-dir "~/Homework/styles/")
    )
#+end_src

* Reading
** Using PDF-Tools instead of DocView
#+begin_src emacs-lisp 
  (use-package pdf-tools
    :ensure t
    :config
    ;; Ensure pdf-tools is initialized after installation
    (pdf-tools-install)

    ;; Make sure PDFs fit the page by default
    (setq-default pdf-view-display-size 'fit-page)

    ;; Set pdf-view-mode as the default for PDF files
    (add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-view-mode))
    (setq pdf-cache-prefetch-delay 0.1)
    ;; Optional: open PDFs in a new frame by default
    ;; (setq pdf-view-use-new-open t)
    ;; set keybindings
    ;; s-left: image-forward-hscroll 5
    ;; s-right: image-backward-hscroll 5
    ;; s-up: image-previous-line 5
    ;; s-down: image-next-line 5
    (define-key pdf-view-mode-map (kbd "s-<left>") 'image-forward-hscroll)
    (define-key pdf-view-mode-map (kbd "s-<right>") 'image-backward-hscroll)
    (define-key pdf-view-mode-map (kbd "s-<up>") 'image-previous-line)
    (define-key pdf-view-mode-map (kbd "s-<down>") 'image-next-line)
    ;; ok now make it scroll 5x faster
    (define-key pdf-view-mode-map (kbd "C-s-<left>") (lambda () (interactive) (image-forward-hscroll 5)))
    (define-key pdf-view-mode-map (kbd "C-s-<right>") (lambda () (interactive) (image-backward-hscroll 5)))
    (define-key pdf-view-mode-map (kbd "C-s-<up>") (lambda () (interactive) (image-previous-line 5)))
    (define-key pdf-view-mode-map (kbd "C-s-<down>") (lambda () (interactive) (image-next-line 5)))
  )
#+end_src

#+RESULTS:
: t

** /nov.el/ support
Using nov.el for epub reading
#+begin_src emacs-lisp
  (use-package nov
    :straight t
    :mode ("\\.epub\\'" . nov-mode)
    :config
    ;; enable olivetti on all nov buffers
    (add-hook 'nov-mode-hook 'olivetti-mode))
#+end_src
** Use webkit with /nov-xwidget/
Render books in Tim Applevision instead of Stallmanvision.
#+begin_src emacs-lisp
  (use-package nov-xwidget
    :straight (:host github :repo "chenyanming/nov-xwidget")
    :demand t
    :after nov
    :config
    (define-key nov-mode-map (kbd "o") 'nov-xwidget-view)
    (add-hook 'nov-mode-hook 'nov-xwidget-inject-all-files))
#+end_src
** Integrate with Calibre
Use calibre db.
#+begin_src emacs-lisp
  (defun yaqub/calibredb-export-bibtex ()
    (interactive)
    (let ((bibtex-command "calibredb catalog ~/Books/References.bib"))
      (shell-command bibtex-command)))

  (use-package calibredb
    :defer t
    :config
    (setq calibredb-root-dir "~/Books")
    (setq calibredb-db-dir (expand-file-name "metadata.db" calibredb-root-dir))
    (evil-set-initial-state 'calibredb-search-mode 'emacs))
#+end_src
** Text-to-speech 
#+begin_src emacs-lisp 
  ;; Function to speak selected text using macOS's say command
  (defun macos-speak-region (start end)
    "Speak text between START and END using macOS's say command."
    (interactive "r")
    (unless (eq major-mode 'pdf-view-mode)
      (let ((text (shell-quote-argument (buffer-substring-no-properties start end))))
        (start-process-shell-command "macos-speak" nil (concat "say " text))
        (deactivate-mark))))

  ;; Function to speak the entire buffer
  (defun macos-speak-buffer ()
    "Speak the entire buffer using macOS's say command."
    (interactive)
    (macos-speak-region (point-min) (point-max)))

  ;; Function to speak selected text in a PDF opened with pdf-tools
  (defun macos-speak-pdf-selection ()
    "Speak the selected text in a PDF opened with pdf-tools."
    (interactive)
    (when (eq major-mode 'pdf-view-mode)
      (let ((text (mapconcat 'identity (pdf-view-active-region-text) " ")))
        (unless (string-blank-p text)
          (start-process-shell-command "macos-speak" nil (concat "say " (shell-quote-argument text)))
          (pdf-view-deactivate-region)))))

  ;; Function to speak the entire text of the current PDF page
  (defun macos-speak-pdf-page ()
    "Speak the text of the current PDF page."
    (interactive)
    (when (eq major-mode 'pdf-view-mode)
      (let ((text (mapconcat 'identity (pdf-view-active-region-text) " ")))
        (unless (string-blank-p text)
          (start-process-shell-command "macos-speak" nil (concat "say " (shell-quote-argument text)))))))

  ;; Keybindings
  (global-set-key (kbd "C-c s") 'macos-speak-region)
  (global-set-key (kbd "C-c M-s") 'macos-speak-buffer)

  (with-eval-after-load 'pdf-view
    (define-key pdf-view-mode-map (kbd "C-c s") 'macos-speak-pdf-selection)
    (define-key pdf-view-mode-map (kbd "C-c M-s") 'macos-speak-pdf-page))
#+end_src
** Reading Tracker
Integrates with my website
#+begin_src emacs-lisp 
  (defun update-org-tracker-progress ()
    "Update :TRACKER_PROGRESS: in the associated org file with the current page and total pages of the PDF."
    (interactive)
    (let* ((current-buffer (buffer-name))
           (org-file-buffer (if (string-suffix-p ".pdf" current-buffer)
                                (find-buffer-visiting (concat (file-name-sans-extension current-buffer) ".org"))
                              (let ((pdf-buffer (concat (file-name-sans-extension (buffer-name)) ".pdf")))
                                (if (get-buffer pdf-buffer)
                                    (current-buffer)))))
           (pdf-file-buffer (if (string-suffix-p ".pdf" current-buffer)
                                current-buffer
                              (concat (file-name-sans-extension (buffer-name)) ".pdf"))))
      (if org-file-buffer
          (with-current-buffer org-file-buffer
            (save-excursion
              (goto-char (point-min))
              (let ((tracker-progress-exists (re-search-forward "^:TRACKER_PROGRESS:" nil t)))
                (goto-char (point-min))
                (unless (re-search-forward "^:TRACKER_PUBLISHED:" nil t)
                  (goto-char (point-max))
                  (insert "\n:TRACKER_PUBLISHED: " (completing-read "Is the tracker published? (YES/NO): " '("YES" "NO"))))
                (if (get-buffer pdf-file-buffer)
                    (with-current-buffer pdf-file-buffer
                      (let* ((pdf-info (pdf-info-number-of-pages))
                             (current-page (pdf-view-current-page)))
                        (with-current-buffer org-file-buffer
                          (goto-char (point-max))
                          (if tracker-progress-exists
                              (re-search-backward "^:TRACKER_PROGRESS:" nil t)
                            (insert "\n:TRACKER_PROGRESS: "))
                          (insert (format "[%d/%d]" current-page pdf-info))))
                  (message "PDF buffer is not open"))))))
        (message "No associated org file is open."))))

  (defun goto-org-tracker-progress ()
    "Go to the page specified in :TRACKER_PROGRESS: in the associated PDF file."
    (interactive)
    (let* ((current-buffer (buffer-name))
           (pdf-file-buffer (if (string-suffix-p ".org" current-buffer)
                                (concat (file-name-sans-extension current-buffer) ".pdf")
                              (let ((org-buffer (concat (file-name-sans-extension (buffer-name)) ".org")))
                                (if (get-buffer org-buffer)
                                    current-buffer)))))
           (org-file-buffer (if (string-suffix-p ".org" current-buffer)
                                current-buffer
                              (concat (file-name-sans-extension (buffer-name)) ".org"))))
      (if (and org-file-buffer pdf-file-buffer)
          (with-current-buffer org-file-buffer
            (save-excursion
              (goto-char (point-min))
              (if (re-search-forward "^:TRACKER_PROGRESS: \\[\\([0-9]+\\)/[0-9]+\\]" nil t)
                  (let ((page (string-to-number (match-string 1))))
                    (if (get-buffer pdf-file-buffer)
                        (with-current-buffer pdf-file-buffer
                          (pdf-view-goto-page page))
                      (message "PDF buffer is not open")))
                (message ":TRACKER_PROGRESS: property not found."))))
        (message "No associated org or PDF file is open.")))

  (global-set-key (kbd "C-c c t") 'update-org-tracker-progress)
  (global-set-key (kbd "C-c c g") 'goto-org-tracker-progress)
#+end_src
* Calendar Integration
** Org-CalDAV
Disabled


;#+begin_src emacs-lisp 
  (use-package org-caldav
    :ensure t
    :config
    (setq org-caldav-url "https://p63-caldav.icloud.com/12112130846/calendars"
          org-caldav-calendars
          '((:calendar-id "1ca12a70-19c9-4ba6-8a8c-baaa8d913b6a"
                          :files ("~/Orgfiles/roam/00000000000000-todo.org")
                          :inbox "~/Orgfiles/roam/00000000000000-todo.org"))))
    (setq org-icalendar-timezone "Europe/London")
  )

;#+end_src

* EAF
Disabled, old code [[id:9073108A-6DBD-4411-9CEF-03C78ED67754][here]].
* macOS
** macOS fullscreen
#+begin_src emacs-lisp 
  (setq ns-use-native-fullscreen t)
#+end_src

** macOS Mouse
I'm using mitsuharu emacs now, so I'll set mouse scrolling to behave according to my zoomer inclinations

#+begin_src emacs-lisp
  (setq mac-mouse-wheel-smooth-scroll t)
#+end_src

** Property lists
OSX Plist is a library for reading and writing property lists (`.plist` files) as used in OS X.

#+begin_src emacs-lisp
  (use-package osx-plist
    :straight (:host github :repo "gonewest818/osx-plist"))
#+end_src

#+RESULTS:

In addition, emacs should recognize everything that ends in *.plist as XML and do syntax highlighting / company suggestions / etc appropriately.

#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.plist\\'" . xml-mode))
#+end_src 

* Email
** smtpmail-multi
#+BEGIN_SRC emacs-lisp
(use-package smtpmail-multi
  :straight t)
#+END_SRC
** Gnus
#+BEGIN_SRC emacs-lisp
(use-package gnus
  :straight t
  :config
  (load "~/.gnus.el"))
#+END_SRC
* AI Tools
Currently, this is in a later part of the config because of my ~ns-keychain~ functions that I'm using for the username and password(s) and API keys and stuff. Dunno if this is the best idea.
** Github Copilot
A lot of the functions here are stolen and very-slightly-modified from Robert Krahn's [[https://robert.kra.hn/posts/2023-02-22-copilot-emacs-setup][blog post]] on setting up Copilot in emacs.

#+begin_src emacs-lisp
  (use-package copilot
    :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
    :ensure t
    :config
    (define-key copilot-mode-map (kbd "C-s-<next>") #'copilot-next-completion)
    (define-key copilot-mode-map (kbd "C-s-<prior>") #'copilot-previous-completion)
    (define-key copilot-mode-map (kbd "C-s-<right>") #'copilot-accept-completion-by-word)
    (define-key copilot-mode-map (kbd "C-s-<down>") #'copilot-accept-completion-by-line)
    (define-key global-map (kbd "C-s-<return>") #'yaqub/copilot-complete-or-accept))

  (defun yaqub/copilot-complete-or-accept ()
    "Command that either triggers a completion or accepts one if one
  is available. Useful if you tend to hammer your keys like I do."
    (interactive)
    ;; Turn on copilot-mode if it's not already active
    (unless (bound-and-true-p copilot-mode)
      (copilot-mode 1))
    (if (copilot--overlay-visible)
        (progn
          (copilot-accept-completion)
          (open-line 1)
          (next-line))
      (copilot-complete)))
#+end_src 
** GPTEl
#+begin_src emacs-lisp
  (use-package gptel
    :straight t)
#+end_src
* Anki Integration
#+begin_src emacs-lisp 
  (use-package anki-editor
    :straight t
    :config
    (global-set-key (kbd "C-c a a") 'anki-editor-insert-note)
    (global-set-key (kbd "C-c a c") 'anki-editor-cloze-region)
    (global-set-key (kbd "C-c a p") 'anki-editor-push-notes))
#+end_src

* Minibuffer Shortcuts
#+begin_src emacs-lisp 
  ;; the command "eval-init" evaluates init.el
  (defun eval-init ()
    (interactive)
    (load-file "~/.emacs.d/init.el"))

  ;; the command "home" opens home orgfile 
  (defun home ()
    (interactive)
    (find-file "~/Orgfiles/roam/00000000000000-home.org"))

  ;; the command "todo" opens todo orgfile
  (defun todo ()
    (interactive)
    (find-file "~/Orgfiles/roam/00000000000000-todo.org"))

  ;; the command "yaqubmacs" opens dired at ~/Development/yaqubmacs
  (defun yaqubmacs ()
    (interactive)
    (dired "~/Development/yaqubmacs"))

  ;; the command nt opens a new term
  (defun nt ()
    "Open a new terminal and prompt for a name."
    (interactive)
    (let ((name (read-string "Terminal name: ")))
      (ansi-term "/bin/zsh" (concat "terminal<" name ">"))))

  ;; the command nesh opens a new eshell
  (defun nesh ()
    "Open a new eshell and prompt for a name."
    (interactive)
    (let ((name (read-string "Eshell name: ")))
      (let ((buffer (generate-new-buffer (concat "*eshell*<" name ">"))))
        (with-current-buffer buffer
          (eshell))
        (switch-to-buffer buffer))))
#+end_src

#+RESULTS:
: nesh


* Server Config

I start up emacs in server mode so I can control it from other parts of the OS.

#+begin_src emacs-lisp 
  (require 'server)
  (unless (server-running-p)
    (server-start))
#+end_src


** Helper functions for the rest of the OS
I use shortcuts to trigger these from context menus.

#+begin_src emacs-lisp
  (defun open-new-eshell-at (dir)
    "Open a new eshell buffer at the specified directory DIR."
    (interactive "Directory: ") ; Ask for the directory interactively
    (let ((default-directory (expand-file-name dir))) ; Ensure the directory path is absolute
      (eshell 'N))) ; 'N ensures a new eshell buffer is created
#+end_src

