#+PROPERTY: header-args :tangle /Users/yaqub/.emacs.d/init.el
* Bootstrap
This section is about setting up straight.el and use-package, which we'll use to manage packages.

** Bootstrap Straight and use-package
#+begin_src emacs-lisp
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src

* Basics
** Bind-key

Need this to work in order to bind keys to packages I install.

#+begin_src emacs-lisp
(use-package bind-key
  :straight t)
#+end_src
** Mitsuharu keybindings
Make mitsuharu keybindings behave like mainline emacs (so command is the super key)
#+begin_src emacs-lisp
  (setq mac-option-modifier 'meta)     ; Set option key as META
  (setq mac-command-modifier 'super)   ; Set cmd key as SUPER
#+end_src
** Silence the bell
#+begin_src emacs-lisp 
  (setq ring-bell-function 'ignore)
#+end_src
** Silence the splash screen
#+begin_src emacs-lisp 
  (setq inhibit-startup-message t)
  (setq initial-buffer-choice t)
#+end_src
** File Backups
Backup files in a hidden ~.saves~ directory, so they don't cloud up ~ls~
#+begin_src emacs-lisp
  (setq backup-directory-alist `(("." . "~/.saves")))
  (setq backup-by-copying t)
#+end_src
** Automatically tangle this config
#+begin_src emacs-lisp
  (defun yaqub/tangle-if-org-in-yaqubmacs ()
    "If the saved file is an .org file within ~/Development/yaqubmacs, tangle it."
    (let ((target-dir (expand-file-name "~/Development/yaqubmacs")))
      (when (and (string-suffix-p ".org" buffer-file-name)
                 (eq major-mode 'org-mode)
                 (string-prefix-p target-dir buffer-file-name))
        (org-babel-tangle))))

  (add-hook 'after-save-hook 'yaqub/tangle-if-org-in-yaqubmacs)
#+end_src
* Aesthetics
This section deals with the aesthetic aspects of our Emacs setup.
** Define fonts
#+begin_src emacs-lisp
  (setq yaqub/font-monospace "Iosevka")
  (setq yaqub/font-variable-serif "CMU Serif")
  (setq yaqub/font-variable-sans "CMU Bright")
  
  ;; Ok, now define fonts on emacs' end
  (set-face-attribute 'default nil :font yaqub/font-monospace :height 180)
  (set-face-attribute 'variable-pitch nil :font yaqub/font-variable-serif :inherit 'default) 
#+end_src
** UI Changes
#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (toggle-scroll-bar -1)
  (tool-bar-mode -1)
  (set-frame-font
   (format "%s-%d" yaqub/font-monospace 18)
   nil t)
#+end_src

We can also do a transparent title bar on macOS:

#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark))
#+end_src
** Install and Enable angloid-theme
#+begin_src emacs-lisp
  (use-package atom-one-dark-theme
    :straight t
    :config
    (load-theme 'atom-one-dark t))
#+end_src
** Setup all-the-icons
All-the-icons is a package to use icons in your Emacs.

#+begin_src emacs-lisp
  (use-package all-the-icons
    :straight (all-the-icons :type git :host github :repo "domtronn/all-the-icons.el" :branch "svg" :files (:defaults "svg"))
    :if (display-graphic-p))
#+end_src

We can also configure all-the-icons to be used with dired

#+begin_src emacs-lisp
  (use-package all-the-icons-dired
    :straight (all-the-icons-dired
  	     :type git
  	     :host github
  	     :repo "jtbm37/all-the-icons-dired")
    :config
    (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+end_src

** Setup modeline
*** Moody
Moody is a package for creating attractive mode-lines.

#+begin_src emacs-lisp
(use-package moody
  :straight t
  :config
  (setq x-underline-at-descent-line t)
  (moody-replace-mode-line-buffer-identification)
  (moody-replace-vc-mode))
#+end_src

*** Minions
Minions is a package for managing and organizing minor-mode lighters in the mode-line.

#+begin_src emacs-lisp
(use-package minions
  :straight t
  :config
  (setq minions-mode-line-lighter "M")
  (setq minions-mode-line-delimiters '("" . ""))
  (minions-mode 1))
#+end_src
** Setup Olivetti-mode
We'll enable olivetti mode whenever we enter org mode.
#+begin_src emacs-lisp
  (use-package olivetti
    :straight t)
#+end_src
* Navigation
This section is about setting up tools that help us navigate our buffers and files more efficiently.
** Setup Ivy and Counsel
#+begin_src emacs-lisp
  (use-package ivy
    :straight t
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package counsel
    :straight t
    :bind (("C-M-j" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :config
    (counsel-mode 1))
#+end_src

** Which-Key
Which-Key is a package that displays a popup listing the possible keys to complete a command, menu, etc.

#+begin_src emacs-lisp
(use-package which-key
  :straight t
  :init
  (which-key-mode)
  :config
  ;; Reduce the delay before which-key popup appears
  (setq which-key-idle-delay 0.3)
  ;; Set the width of the which-key popup window
  (setq which-key-side-window-max-width 0.33)
  ;; Set the location of the which-key popup window to the bottom
  (setq which-key-side-window-location 'bottom))
#+end_src

** Setup Evil-mode
Evil-mode provides Vim keybindings in Emacs.

#+begin_src emacs-lisp
  (defun yaqub/jump-to-scratch-or-quit (orig-fun &rest args)
    "Switch to *scratch* buffer when :q is executed on single window, or quit otherwise."
    (if (one-window-p t)
        (if (not (string= (buffer-name) "*scratch*"))
            (switch-to-buffer "*scratch*"))
      (apply orig-fun args)))

  (use-package evil
    :straight t
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    :config
    (evil-mode 1)
    (advice-add 'evil-quit :around 'yaqub/jump-to-scratch-or-quit))

  (use-package evil-collection
    :straight t
    :after evil
    :config
    (evil-collection-init))
#+end_src
**** Multiple cursors in evil-mode
#+begin_src emacs-lisp
  (use-package evil-mc
    :straight t
    :config
    (global-evil-mc-mode 1))
#+end_src
** Dirvish
Dirvish is an improved version of dired. Old dired settings [[id:41303942-1C05-429C-A876-858BAADB853F][here.]]

#+begin_src emacs-lisp 
  (use-package dirvish
    :straight t
    :config
    (dirvish-override-dired-mode))
#+end_src
* Coding
This section is about setting up tools to help us write code more efficiently.

** Enable line numbers in prog-mode
#+begin_src emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

** Setup Yasnippet
Yasnippet is a template system for Emacs.

#+begin_src emacs-lisp
  (use-package yasnippet
    :straight t
    :init
    (yas-global-mode 1))
#+end_src

** Setup Company-mode
Company mode is a text completion framework.

#+begin_src emacs-lisp
  (use-package company
    :straight t
    :init
    (global-company-mode))
#+end_src

*** Setup Company-box
Company-box is a frontend for company-mode, it provides a dropdown menu interface for completions.

#+begin_src emacs-lisp
  (use-package company-box
    :straight t
    :hook (company-mode . company-box-mode))
#+end_src
** Magit
Magit is an interface to the version control system Git, implemented as an Emacs package. It aspires to be a complete Git porcelain.

#+begin_src emacs-lisp
(use-package magit
  :straight t
  :bind (("C-x g" . magit-status)))
#+end_src
** Javascript
#+begin_src emacs-lisp 
  (add-hook 'js-mode-hook
  	  (lambda ()
  	    (setq js-indent-level 2)
  	    (setq indent-tabs-mode nil)))
#+end_src
* Writing
This section is about setting up tools to help us write prose more efficiently; mostly org config.
** Global bibliography variables
#+begin_src emacs-lisp 
  (setq yaqub/global-bibliography '("~/Books/catalog.bib"
  			   "~/Articles/References.bib")
        yaqub/global-library-path '("~/Books/" "~/Articles/")
        yaqub/global-notes-path "~/Notes/")
#+end_src
** Setup Org
Here, we separate the org setup into its own function for clarity.

#+begin_src emacs-lisp
  (defun yaqub/org-font-setup ()
    ;; These are the sizes I want.
    (let ((org-level-font-scale '(
  			  (1 . 1.5)
  			  (2 . 1.375)
  			  (3 . 1.25)
  			  (4 . 1.125)
  			  (5 . 1.0)
  			  (6 . 1.0)
  			  (7 . 1.0)
  			  (8 . 1.0)
  			  )))
      ;; Iterate through all the org levels, and make them the same colour as 'default.
      (dolist (level (number-sequence 1 8))
  	     (let* ((org-level-face (intern (format "org-level-%d" level)))
  	            (org-level-size (cdr (assoc level org-level-font-scale))))
  	     (when org-level-size
  	       (set-face-attribute org-level-face nil
  				   :font yaqub/font-variable-serif
  				   :foreground (face-attribute 'default :foreground)
  				   :weight 'bold
  				   :height org-level-size)))))
    
    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-code nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block-begin-line nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-block-end-line nil
  			:font yaqub/font-monospace
  			:inherit '(shadow fixed-pitch)))

  (use-package org
    :straight t
    :config
    (yaqub/org-font-setup)
    (add-hook 'org-mode-hook 'variable-pitch-mode)
    (setq org-hide-emphasis-markers t)
    (setq org-startup-indented t)
    ;; org-cite-bibliography will be used for all bib-related files
    (setq org-cite-global-bibliography yaqub/global-bibliography)
    ;; Enable olivetti on all org buffers
    (add-hook 'org-mode-hook 'olivetti-mode))
#+end_src
*** Org-roam

Very important.
#+begin_src emacs-lisp
  (use-package org-roam
    :straight t
    :custom
    (org-roam-directory "~/Orgfiles/roam")
    :config
    (setq org-roam-capture-templates
          '(("d" "default" plain
     "%?"
     :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
     :unnarrowed t)
            
            ("r" "bibliography reference" plain
             (file "~/Orgfiles/roam/templates/orb.org")
             :target
             (file+head "references/${citekey}.org" "#+title: ${title}\n"))))
    :bind (("C-c n f" . org-roam-node-find)
           ("C-c n i" . org-roam-node-insert)
           ("C-c n g" . org-roam-graph)
           ("C-c n c" . org-roam-capture)
           ("C-c n d" . org-roam-dailies-goto-today)
           ("C-c n D" . org-roam-dailies-goto-date)))
#+end_src
*** Ivy-bibtex
#+begin_src emacs-lisp
  (use-package ivy-bibtex
  :straight t
  :config
  (setq bibtex-completion-bibliography yaqub/global-bibliography
  	bibtex-completion-library-path yaqub/global-library-path
  	bibtex-completion-pdf-field "file")
  (ivy-set-actions   
   'ivy-bibtex
   '(("e" ivy-bibtex-edit-notes "Edit notes" ivy-bibtex-edit-notes))))
#+end_src
*** Citar
This plugin provides the basic functionality of ~org-ref~, but uses the ~org-cite~ syntax instead of breaking with what's built into emacs.

#+begin_src emacs-lisp
  (use-package citar
    :straight t
    :custom
    (org-cite-insert-processor 'citar)
    (org-cite-follow-processor 'citar)
    (org-cite-activate-processor 'citar)
    (citar-bibliography org-cite-global-bibliography)
    :hook
    (LaTeX-mode . citar-capf-setup)
    (org-mode . citar-capf-setup))

#+end_src
*** Org-roam-bibtex
#+begin_src emacs-lisp
  (use-package org-roam-bibtex
    :after org-roam
    :config
    (setq orb-preformat-keywords
        '("citekey" "title" "url" "author-or-editor" "keywords" "file")
        orb-process-file-keyword t
        orb-attached-file-extensions '("epub" "pdf"))
    (org-roam-bibtex-mode))
#+end_src
*** Org-modern
Only temporarily re-deploying org-modern, until the font locking issue is fixed in svg-tag-mode (cf. [[https://github.com/rougier/svg-tag-mode/issues/48][issue]])

#+begin_src emacs-lisp
  (use-package org-modern
    :straight t
    :config
    (global-org-modern-mode))
#+end_src
*** Org-dashboard
#+begin_src emacs-lisp
  (use-package org-dashboard
    :straight t)
#+end_src
*** Org-noter
#+begin_src emacs-lisp
  (use-package org-noter
    :after (:all org nov pdf-tools)
    :straight t)

  (defun yaqub/org-noter-here (&optional arg)
    (interactive "P")
    (let ((org-noter-always-create-frame nil))
      (org-noter arg)))

  (global-set-key (kbd "C-c N") 'yaqub/org-noter-here)
#+end_src
* Reading
** Using PDF-Tools instead of DocView
#+begin_src emacs-lisp 
  (use-package pdf-tools
    :ensure t
    :config
    ;; Ensure pdf-tools is initialized after installation
    (pdf-tools-install)

    ;; Make sure PDFs fit the page by default
    (setq-default pdf-view-display-size 'fit-page)

    ;; Set pdf-view-mode as the default for PDF files
    (add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-view-mode))

    ;; Optional: open PDFs in a new frame by default
    ;; (setq pdf-view-use-new-open t)
  )
#+end_src
** /nov.el/ support
Using nov.el for epub reading
#+begin_src emacs-lisp
  (use-package nov
    :straight t
    :mode ("\\.epub\\'" . nov-mode)
    :config
    ;; enable olivetti on all nov buffers
    (add-hook 'nov-mode-hook 'olivetti-mode))
#+end_src
** Use webkit with /nov-xwidget/
Render books in Tim Applevision instead of Stallmanvision.
#+begin_src emacs-lisp
  (use-package nov-xwidget
    :straight (:host github :repo "chenyanming/nov-xwidget")
    :demand t
    :after nov
    :config
    (define-key nov-mode-map (kbd "o") 'nov-xwidget-view)
    (add-hook 'nov-mode-hook 'nov-xwidget-inject-all-files))
#+end_src
** Integrate with Calibre
Use calibre db.
#+begin_src emacs-lisp
  (defun yaqub/calibredb-export-bibtex ()
    (interactive)
    (let ((bibtex-command "calibredb catalog ~/Books/References.bib"))
      (shell-command bibtex-command)))

  (use-package calibredb
    :defer t
    :config
    (setq calibredb-root-dir "~/Books")
    (setq calibredb-db-dir (expand-file-name "metadata.db" calibredb-root-dir))
    (evil-set-initial-state 'calibredb-search-mode 'emacs))
#+end_src
** Integrate with Zotero
#+begin_src emacs-lisp
  (defun zotra-download-attachment-for-current-entry ()
    (interactive)
    (save-excursion
      (bibtex-beginning-of-entry)
      (let* ((entry (bibtex-parse-entry t))
             (key (cdr (assoc "=key=" entry)))
             (url (cdr (assoc "url" entry)))
             (filename (concat key ".pdf"))
             (filename (when entry
                         (zotra-download-attachment-from-url
                          url nil filename))))
        (when filename
          (bibtex-make-field (list "File" nil filename) t)))))

  (use-package zotra
    :straight t
    :config
    (setq zotra-cli-command '("node" "~/Development/zotra-cli/bin/index.js"))
    (add-hook 'zotra-after-get-bibtex-entry-hook
  	    'zotra-download-attachment-for-current-entry))
#+end_src
* macOS
** macOS fullscreen
#+begin_src emacs-lisp 
  (setq ns-use-native-fullscreen t)
#+end_src
** macOS Mouse
I'm using mitsuharu emacs now, so I'll set mouse scrolling to behave according to my zoomer inclinations

#+begin_src emacs-lisp
  (setq mac-mouse-wheel-smooth-scroll t)
#+end_src

** Getting passwords from macOS keychain
Here, I'm declaring two new functions that use Apple's ~security~ command to access passwords in the macOS keychain. I can add Keychain entries with [[elisp:(shell-command "open '/System/Applications/Utilities/Keychain Access.app'")][Keychain Access]].

#+begin_src emacs-lisp
  (use-package ns-keychain
    :straight (:host github :repo "yaqubroli/ns-keychain.el"))
#+end_src
** Property lists
OSX Plist is a library for reading and writing property lists (`.plist` files) as used in OS X.

#+begin_src emacs-lisp
  (use-package osx-plist
    :straight (:host github :repo "gonewest818/osx-plist"))
#+end_src

In addition, emacs should recognize everything that ends in *.plist as XML and do syntax highlighting / company suggestions / etc appropriately.

#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.plist\\'" . xml-mode))
#+end_src 

* Email
** smtpmail-multi
#+BEGIN_SRC emacs-lisp
(use-package smtpmail-multi
  :straight t)
#+END_SRC
** Gnus
#+BEGIN_SRC emacs-lisp
(use-package gnus
  :straight t
  :config
  (load "~/.gnus.el"))
#+END_SRC
* AI Tools
Currently, this is in a later part of the config because of my ~ns-keychain~ functions that I'm using for the username and password(s) and API keys and stuff. Dunno if this is the best idea.

** OpenAI 
This library is required for ChatGPT, DeepL etc to function
#+begin_src emacs-lisp 
  (use-package openai
    :straight (openai :type git :host github :repo "emacs-openai/openai")
    :config (setq openai-key (ns-keychain-get-generic-password "OpenAI" "walchuk2018@icloud.com")))
  #+end_src
*** ChatGPT
#+begin_src emacs-lisp
  (use-package chatgpt
    :straight (chatgpt :type git :host github :repo "emacs-openai/chatgpt")
    :config
    (add-hook 'chatgpt-input-mode-hook (lambda () (evil-insert 1)))
    (setq chatgpt-model "gpt-4")
    (setq chatgpt-window-prompt ""))
#+end_src
** Github Copilot
A lot of the functions here are stolen and very-slightly-modified from Robert Krahn's [[https://robert.kra.hn/posts/2023-02-22-copilot-emacs-setup][blog post]] on setting up Copilot in emacs.

#+begin_src emacs-lisp
  (use-package copilot
    :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
    :ensure t
    :config
    (define-key copilot-mode-map (kbd "C-s-<next>") #'copilot-next-completion)
    (define-key copilot-mode-map (kbd "C-s-<prior>") #'copilot-previous-completion)
    (define-key copilot-mode-map (kbd "C-s-<right>") #'copilot-accept-completion-by-word)
    (define-key copilot-mode-map (kbd "C-s-<down>") #'copilot-accept-completion-by-line)
    (define-key global-map (kbd "C-s-<return>") #'yaqub/copilot-complete-or-accept)
    :hook (prog-mode . copilot-mode))

  (defun yaqub/copilot-complete-or-accept ()
    "Command that either triggers a completion or accepts one if one
  is available. Useful if you tend to hammer your keys like I do."
    (interactive)
    ;; Turn on copilot-mode if it's not already active
    (unless (bound-and-true-p copilot-mode)
      (copilot-mode 1))
    (if (copilot--overlay-visible)
        (progn
          (copilot-accept-completion)
          (open-line 1)
          (next-line))
      (copilot-complete)))
#+end_src 

* Minibuffer Shortcuts
#+begin_src emacs-lisp 
  ;; the command "eval-init" evaluates init.el
  (defun eval-init ()
    (interactive)
    (load-file "~/.emacs.d/init.el"))

  ;; the command "home" opens dired at ~/
  (defun home ()
    (interactive)
    (dired "~/"))

  ;; the command "dev" opens dired at ~/Development
  (defun dev ()
    (interactive)
    (dired "~/Development"))

  ;; the command "org" opens dired at ~/Orgfiles
  (defun org ()
    (interactive)
    (dired "~/Orgfiles"))

  ;; the command "yaqubmacs" opens dired at ~/Development/yaqubmacs
  (defun yaqubmacs ()
    (interactive)
    (dired "~/Development/yaqubmacs"))

  (defun bib ()
    (interactive)
    (ivy-bibtex))
#+end_src
